Models/DataAccess.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace SearchPersons.Models
{
    public class DataAccess
    {
        string connstring = ConfigurationManager.ConnectionStrings["constr"].ConnectionString;
        public List<PersonInfo> getAllPersons(string personname="") {
            List<PersonInfo> lstPersons = new List<PersonInfo>();         
            try {
                SqlConnection conn = new SqlConnection(connstring);
                SqlCommand cmd = new SqlCommand("uspPersonSearch", conn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@person_name",personname);
                conn.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    PersonInfo persons = new PersonInfo();
                    persons.PersonId = Convert.ToInt32(rdr["person_id"]);
                    persons.FirstName = rdr["first_name"].ToString();
                    persons.LastName = rdr["last_name"].ToString();
                    persons.Gender = Convert.ToChar(rdr["gender"]);
                    persons.StateCode = rdr["state_code"].ToString();
                    persons.DOB = Convert.ToDateTime(rdr["DOB"]);
                    lstPersons.Add(persons);
                }
                conn.Close();
                
            }
            catch (Exception ex) { throw ex; }
            return lstPersons;
        }

        public bool updatePerson(int personid, string firstname, string lastname, char gender, DateTime dob, int stateid) {
            bool result = false;
            try
            {
                SqlConnection conn = new SqlConnection(connstring);
                SqlCommand cmd = new SqlCommand("uspPersonSearch", conn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@person_id", personid);
                cmd.Parameters.AddWithValue("@first_name", firstname);
                cmd.Parameters.AddWithValue("@last_name", lastname);
                cmd.Parameters.AddWithValue("@gender", gender);
                cmd.Parameters.AddWithValue("@state_id", stateid);
                cmd.Parameters.AddWithValue("@dob", dob);
                conn.Open();
               int rows= cmd.ExecuteNonQuery();
                if (rows > 0) { result=true; }
                conn.Close();
            }
            catch (Exception ex) { throw ex; }
            return result;
        }
        public List<StateInfo> getStates() {
            

               List<StateInfo> lstStates = new List<StateInfo>();
            try
            {
                SqlConnection conn = new SqlConnection(connstring);
                SqlCommand cmd = new SqlCommand("uspStatesList", conn);
                cmd.CommandType = CommandType.StoredProcedure;
                conn.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    StateInfo states = new StateInfo();
                    states.StateId = Convert.ToInt32(rdr["state_id"]);
                    states.StateCode = rdr["state_code"].ToString();                
                    lstStates.Add(states);
                }
                conn.Close();

            }
            catch (Exception ex) { throw ex; }
            return lstStates;



        }
    }
}

Models/PersonInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SearchPersons.Models
{
    public class PersonInfo
    {
      
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public char Gender { get; set; }        
        public DateTime DOB { get; set; }
        public string StateCode { get; set; }
    }
    public class StateInfo
    {
        public int StateId { get; set; }
        public string StateCode { get; set; }
    }

 

}

Controllers/PersonInfoController.cs
using SearchPersons.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace SearchPersons.Controllers
{
    public class PersonInfoController : Controller
    {
        // GET: PersonInfo
        public ActionResult Index(string personname="")
        {
           
            List<PersonInfo> lstPersons = new List<PersonInfo>();
            DataAccess da = new DataAccess();
            lstPersons=  da.getAllPersons(personname);
            List<StateInfo> lststates = new List<StateInfo>();
            lststates = da.getStates();
           


            return View(lstPersons);
        }
        [HttpPost]
        public ActionResult Index(int personid,string firstname,string lastname,char gender,DateTime dob,int stateid) {        
            DataAccess da = new DataAccess();
            da.updatePerson(personid,firstname,lastname,gender,dob,stateid);
            return View();
        }
    }
}

Views/PersonInfo/Index.cshtml

@model IEnumerable<SearchPersons.Models.PersonInfo>

@{
	ViewBag.Title = "Index";
}
<script src="~/Scripts/PersonInfo/PersonInfo.js"></script>
<style>
	.input-group {
		display: block;
	}
</style>
<div class="page-header">
	<h2>Person Info</h2>
	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addperson"> Add Person</button>
</div>


<div class="input-group">
	<input type="text" id="txtSearch" class="form-control" maxlength="10" onkeyup="textupdate()" placeholder="Search" name="search">
	<button id="btnSearch" class="btn btn-default" type="submit" onclick="location.href='@Url.Action("Index", "PersonInfo")?personname=' + document.getElementById('txtSearch').value" disabled>
		<i class="glyphicon glyphicon-search"></i>
	</button>

</div>
<br />

<div class="container">

	<div class="modal" id="addperson">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Add Person</h4>
				</div>
				<div class="modal-body">
					<table class="table table-condensed">
						<tr>
							<td>
								<label>First Name:</label>
							</td>
							<td>
								<input type="text" class="form-control" id="firstname" placeholder="First Name" name="firstname">
							</td>
						</tr>
						<tr>
							<td>
								<label>Last Name:</label>
							</td>
							<td>
								<input type="text" class="form-control" id="lastname" placeholder="Last Name" name="lastname">
							</td>
						</tr>
						<tr>
							<td>
								<label>Gender:</label>
							</td>
							<td>
								<select type="text" class="form-control" id="gender" placeholder="Gender" name="gender">
									<option>Select Gender</option>
									<option value="Male">M</option>
									<option value="FeMale">F</option>
								</select>
							</td>
						</tr>
						<tr>
							<td>
								<label>State:</label>
							</td>
							<td>
								<select type="text" class="form-control" id="state" placeholder="State" name="state" />
							</td>
						</tr>
						<tr>
							<td>
								<label>DOB:</label>
							</td>
							<td>
								<input id="date" class="form-control" type="date">
							</td>
						</tr>
					</table>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" onclick="validatepersons()">Submit</button>
					<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>


</div>
<div class="panel panel-default pre-scrollable">

	<table class="table table-striped table-bordered table-responsive table-condensed table-hover">
		<thead>
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Gender</th>
				<th>State</th>
				<th>DOB</th>
			</tr>
		</thead>
		<tbody>
			
				@foreach (var items in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => items.FirstName)
						</td>
						<td>
							@Html.DisplayFor(modelItem => items.LastName)
						</td>
						<td>
							@Html.DisplayFor(modelItem => items.Gender)
						</td>
						<td>
							@Html.DisplayFor(modelItem => items.StateCode)
						</td>
						<td>
							@Html.DisplayFor(modelItem => items.DOB)
						</td>
						<td>
							<button class="btn glyphicon glyphicon-pencil" data-toggle="modal" data-target="#addperson" />
						</td>
					</tr>

				}

			

		</tbody>
	</table>
</div>




Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Search Persons", "Index", "PersonInfo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Person Info App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>